version: 2

updates:

  #
  # Gradle dependencies
  #
  - package-ecosystem: "gradle"
    directory: "/iot-c"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:20"
      timezone: "UTC"

    open-pull-requests-limit: 10

    commit-message:
      prefix: "dep-gradle"

    labels:
      - dependencies
      - java

    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot*"

      aws:
        patterns:
          - "software.amazon.awssdk*"

      test:
        patterns:
          - "org.junit*"
          - "org.mockito*"
  #
  # GitHub Actions
  #
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:20"
      timezone: "UTC"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "dep-github-actions"

    labels:
      - dependencies
      - github-actions

  #
  # Dockerfiles
  #
  - package-ecosystem: "docker"
    directory: "/iot-c/collector-a-to-c"
    schedule:
      interval: "friday"
      day: "monday"
      time: "12:20"
      timezone: "UTC"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "dep-docker"

    labels:
      - dependencies
      - docker

    groups:
      docker-base-images:
        patterns:
          - "*"